-- Plan comptable PME suisse recommandé par FIDUCIAIRE|SUISSE
-- Migration 0002 — Seed comptes essentiels (~90 comptes)

INSERT OR IGNORE INTO accounts (id, code, name, account_type, description, is_active) VALUES
-- ACTIFS
(lower(hex(randomblob(16))), '1000', 'Caisse', 'asset', 'Espèces en caisse', 1),
(lower(hex(randomblob(16))), '1010', 'Caisse postale / Compte courant postal', 'asset', 'CCP / PostFinance', 1),
(lower(hex(randomblob(16))), '1020', 'Banque (compte courant)', 'asset', 'Compte bancaire courant', 1),
(lower(hex(randomblob(16))), '1060', 'Titres cotés (court terme)', 'asset', 'Placements financiers à court terme', 1),
(lower(hex(randomblob(16))), '1100', 'Débiteurs suisses', 'asset', 'Créances clients domiciliés en Suisse', 1),
(lower(hex(randomblob(16))), '1101', 'Débiteurs étrangers', 'asset', 'Créances clients domiciliés à l''étranger', 1),
(lower(hex(randomblob(16))), '1109', 'Provision pour créances douteuses', 'asset', 'Correction de valeur sur débiteurs douteux', 1),
(lower(hex(randomblob(16))), '1170', 'Impôt anticipé à récupérer', 'asset', 'Impôt anticipé AFC à rembourser', 1),
(lower(hex(randomblob(16))), '1176', 'Impôt sur le bénéfice (acomptes)', 'asset', 'Acomptes versés sur impôt bénéfice', 1),
(lower(hex(randomblob(16))), '1200', 'Stocks de marchandises', 'asset', 'Marchandises destinées à la revente', 1),
(lower(hex(randomblob(16))), '1210', 'Stocks de matières premières', 'asset', 'Matières premières et auxiliaires', 1),
(lower(hex(randomblob(16))), '1300', 'Charges payées d''avance', 'asset', 'Régularisation actif — charges futures', 1),
(lower(hex(randomblob(16))), '1301', 'Produits à recevoir', 'asset', 'Régularisation actif — produits courus', 1),
(lower(hex(randomblob(16))), '1440', 'Mobilier et machines de bureau', 'asset', 'Immobilisations mobilier bureau', 1),
(lower(hex(randomblob(16))), '1441', 'Machines et équipements', 'asset', 'Immobilisations machines industrielles', 1),
(lower(hex(randomblob(16))), '1500', 'Immobilisations corporelles', 'asset', 'Valeurs immobilisées corporelles générales', 1),
(lower(hex(randomblob(16))), '1510', 'Véhicules', 'asset', 'Véhicules d''exploitation', 1),
(lower(hex(randomblob(16))), '1520', 'Mobilier d''exploitation', 'asset', 'Mobilier de l''entreprise', 1),
(lower(hex(randomblob(16))), '1530', 'Machines et appareils', 'asset', 'Parc machines de production', 1),
(lower(hex(randomblob(16))), '1540', 'Informatique et systèmes', 'asset', 'Matériel informatique et logiciels', 1),
(lower(hex(randomblob(16))), '1600', 'Immeubles (exploitation)', 'asset', 'Bâtiments et terrains d''exploitation', 1),
(lower(hex(randomblob(16))), '1700', 'Participations', 'asset', 'Participations dans des sociétés liées', 1),
(lower(hex(randomblob(16))), '1800', 'Autres créances à long terme', 'asset', 'Prêts et créances long terme divers', 1),
-- PASSIFS — DETTES
(lower(hex(randomblob(16))), '2000', 'Créanciers (fournisseurs)', 'liability', 'Dettes envers les fournisseurs', 1),
(lower(hex(randomblob(16))), '2100', 'Dettes bancaires court terme', 'liability', 'Crédits bancaires remboursables < 1 an', 1),
(lower(hex(randomblob(16))), '2200', 'Dettes à court terme', 'liability', 'Autres dettes exigibles à court terme', 1),
(lower(hex(randomblob(16))), '2261', 'TVA due (dette fiscale)', 'liability', 'TVA collectée à reverser à l''AFC', 1),
(lower(hex(randomblob(16))), '2262', 'TVA déductible (créance fiscale)', 'liability', 'TVA récupérable sur achats', 1),
(lower(hex(randomblob(16))), '2270', 'Impôts dus', 'liability', 'Impôts communaux, cantonaux et fédéraux dus', 1),
(lower(hex(randomblob(16))), '2300', 'Produits constatés d''avance', 'liability', 'Régularisation passif — produits différés', 1),
(lower(hex(randomblob(16))), '2301', 'Charges à payer', 'liability', 'Régularisation passif — charges courues', 1),
(lower(hex(randomblob(16))), '2330', 'Dividendes à payer', 'liability', 'Dividendes décidés non encore versés', 1),
(lower(hex(randomblob(16))), '2400', 'Emprunts hypothécaires', 'liability', 'Dettes hypothécaires sur immeubles', 1),
(lower(hex(randomblob(16))), '2420', 'Prêts à long terme', 'liability', 'Emprunts à long terme non hypothécaires', 1),
(lower(hex(randomblob(16))), '2430', 'Obligations', 'liability', 'Emprunts obligataires émis', 1),
(lower(hex(randomblob(16))), '2500', 'Provisions pour risques', 'liability', 'Provisions pour risques et charges futurs', 1),
(lower(hex(randomblob(16))), '2600', 'Autres dettes à long terme', 'liability', 'Dettes diverses à plus d''un an', 1),
-- CAPITAUX PROPRES
(lower(hex(randomblob(16))), '2800', 'Capital-actions / Capital social', 'equity', 'Capital nominatif libéré', 1),
(lower(hex(randomblob(16))), '2900', 'Réserve légale', 'equity', 'Réserve légale issue des bénéfices (CO 671)', 1),
(lower(hex(randomblob(16))), '2940', 'Réserves facultatives', 'equity', 'Réserves constituées par décision de l''AG', 1),
(lower(hex(randomblob(16))), '2950', 'Bénéfice/Perte reporté(e)', 'equity', 'Report des exercices précédents', 1),
(lower(hex(randomblob(16))), '2960', 'Bénéfice/Perte de l''exercice', 'equity', 'Résultat net de l''exercice en cours', 1),
-- PRODUITS
(lower(hex(randomblob(16))), '3000', 'Produits des ventes (marchandises)', 'revenue', 'Chiffre d''affaires marchandises', 1),
(lower(hex(randomblob(16))), '3200', 'Produits des services', 'revenue', 'Chiffre d''affaires prestations de services', 1),
(lower(hex(randomblob(16))), '3400', 'Produits divers', 'revenue', 'Autres produits liés à l''exploitation', 1),
(lower(hex(randomblob(16))), '3600', 'Variations des stocks (produits finis)', 'revenue', 'Variation nette des stocks produits finis', 1),
(lower(hex(randomblob(16))), '3700', 'Travaux pour compte propre', 'revenue', 'Prestations internes activées', 1),
(lower(hex(randomblob(16))), '3800', 'Autres produits d''exploitation', 'revenue', 'Produits accessoires d''exploitation', 1),
(lower(hex(randomblob(16))), '3900', 'Produits financiers (intérêts)', 'revenue', 'Intérêts créditeurs et revenus financiers', 1),
(lower(hex(randomblob(16))), '3910', 'Produits des participations', 'revenue', 'Dividendes et revenus de participations', 1),
-- CHARGES
(lower(hex(randomblob(16))), '4000', 'Achats de marchandises', 'expense', 'Coût d''achat des marchandises revendues', 1),
(lower(hex(randomblob(16))), '4100', 'Achats de matières premières', 'expense', 'Consommation matières premières et auxiliaires', 1),
(lower(hex(randomblob(16))), '4200', 'Variation des stocks de marchandises', 'expense', 'Ajustement de valeur des stocks marchandises', 1),
(lower(hex(randomblob(16))), '5000', 'Salaires et traitements', 'expense', 'Rémunérations brutes du personnel', 1),
(lower(hex(randomblob(16))), '5010', 'Charges sociales AVS/AC/AI', 'expense', 'Cotisations patronales AVS, AC, AI, APG', 1),
(lower(hex(randomblob(16))), '5020', 'Charges LPP (prévoyance professionnelle)', 'expense', 'Cotisations patronales caisse de pension', 1),
(lower(hex(randomblob(16))), '5030', 'Autres charges du personnel', 'expense', 'Frais de personnel divers (frais, indemnités)', 1),
(lower(hex(randomblob(16))), '5100', 'Formation et perfectionnement', 'expense', 'Formations, cours et perfectionnement personnel', 1),
(lower(hex(randomblob(16))), '5900', 'Compte de résultat (bilan)', 'equity', 'Compte de clôture — virement bénéfice/perte', 1),
(lower(hex(randomblob(16))), '5910', 'Résultat de l''exercice', 'equity', 'Résultat final avant affectation', 1),
(lower(hex(randomblob(16))), '6000', 'Loyer des locaux', 'expense', 'Loyers et charges locatives des locaux', 1),
(lower(hex(randomblob(16))), '6010', 'Entretien et réparations', 'expense', 'Frais d''entretien des bâtiments et équipements', 1),
(lower(hex(randomblob(16))), '6020', 'Frais de véhicule', 'expense', 'Carburant, entretien et assurance véhicules', 1),
(lower(hex(randomblob(16))), '6030', 'Assurances', 'expense', 'Primes d''assurances entreprise', 1),
(lower(hex(randomblob(16))), '6040', 'Énergie et eau', 'expense', 'Électricité, gaz, eau et chauffage', 1),
(lower(hex(randomblob(16))), '6100', 'Administration générale', 'expense', 'Frais d''administration et de gestion générale', 1),
(lower(hex(randomblob(16))), '6110', 'Frais de bureau et fournitures', 'expense', 'Papeterie, fournitures et petits matériels', 1),
(lower(hex(randomblob(16))), '6200', 'Publicité et marketing', 'expense', 'Dépenses publicitaires et marketing', 1),
(lower(hex(randomblob(16))), '6210', 'Frais de représentation', 'expense', 'Repas d''affaires et cadeaux clients', 1),
(lower(hex(randomblob(16))), '6300', 'Frais de transport', 'expense', 'Ports, transports et expéditions', 1),
(lower(hex(randomblob(16))), '6400', 'Amortissements mobilier', 'expense', 'Amortissements sur mobilier de bureau', 1),
(lower(hex(randomblob(16))), '6410', 'Amortissements machines', 'expense', 'Amortissements sur machines et équipements', 1),
(lower(hex(randomblob(16))), '6420', 'Amortissements informatique', 'expense', 'Amortissements matériel et logiciels IT', 1),
(lower(hex(randomblob(16))), '6430', 'Amortissements véhicules', 'expense', 'Amortissements parc véhicules', 1),
(lower(hex(randomblob(16))), '6440', 'Amortissements immobilier', 'expense', 'Amortissements immeubles d''exploitation', 1),
(lower(hex(randomblob(16))), '6500', 'Frais bancaires et charges financières', 'expense', 'Commissions et frais bancaires divers', 1),
(lower(hex(randomblob(16))), '6510', 'Intérêts des dettes', 'expense', 'Intérêts débiteurs sur emprunts et crédits', 1),
(lower(hex(randomblob(16))), '6520', 'Pertes sur débiteurs', 'expense', 'Créances irrécouvrables passées en perte', 1),
(lower(hex(randomblob(16))), '6700', 'Impôts sur le bénéfice', 'expense', 'Impôts directs sur le bénéfice (ICC + IFD)', 1),
(lower(hex(randomblob(16))), '6800', 'Autres charges d''exploitation', 'expense', 'Charges d''exploitation diverses non classées', 1),
(lower(hex(randomblob(16))), '6900', 'Charges exceptionnelles', 'expense', 'Pertes et charges à caractère exceptionnel', 1);
